#!/bin/sh

VERSION=`grep Version ljdump.py | cut -d' ' -f3`

DIR=ljdump-$VERSION
rm -rf $DIR
mkdir $DIR
cp ChangeLog README.txt ljdump.py ljdump.config.sample $DIR/

TARGZ=ljdump-$VERSION.tar.gz
rm $TARGZ
tar czf $TARGZ $DIR/*

ZIP=ljdump-$VERSION.zip
rm $ZIP
zip $ZIP $DIR/*

rm -rf $DIR

md5 $TARGZ
md5 $ZIP
